#pragma once

#define RCOMPONENT_LOG_PREFIX "%s:%d: "
#define RCOMPONENT_LOG_ARGS __FILE_NAME__, __LINE__

#define RCOMPONENT_STREAM_PREFIX \
  __FILE_NAME__ << ":" << __LINE__ << ": "

// ==============================
// DEBUG
// ==============================

#define RCOMPONENT_DEBUG(format_string, ...) \
  RCLCPP_DEBUG(logger_, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_DEBUG_ONCE(format_string, ...) \
  RCLCPP_DEBUG_ONCE(logger_, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_DEBUG_EXPRESSION(cond, format_string, ...) \
  RCLCPP_DEBUG_EXPRESSION(logger_, cond, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_DEBUG_FUNCTION(func, format_string, ...) \
  RCLCPP_DEBUG_FUNCTION(logger_, func, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_DEBUG_SKIPFIRST(format_string, ...) \
  RCLCPP_DEBUG_SKIPFIRST(logger_, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_DEBUG_THROTTLE(rate, format_string, ...) \
  RCLCPP_DEBUG_THROTTLE(logger_, rate, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_DEBUG_SKIPFIRST_THROTTLE(rate, format_string, ...) \
  RCLCPP_DEBUG_SKIPFIRST_THROTTLE(logger_, rate, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_DEBUG_STREAM(args) \
  RCLCPP_DEBUG_STREAM(logger_, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_DEBUG_STREAM_ONCE(args) \
  RCLCPP_DEBUG_STREAM_ONCE(logger_, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_DEBUG_STREAM_EXPRESSION(cond, args) \
  RCLCPP_DEBUG_STREAM_EXPRESSION(logger_, cond, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_DEBUG_STREAM_FUNCTION(func, args) \
  RCLCPP_DEBUG_STREAM_FUNCTION(logger_, func, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_DEBUG_STREAM_SKIPFIRST(args) \
  RCLCPP_DEBUG_STREAM_SKIPFIRST(logger_, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_DEBUG_STREAM_THROTTLE(rate, args) \
  RCLCPP_DEBUG_STREAM_THROTTLE(logger_, rate, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_DEBUG_STREAM_SKIPFIRST_THROTTLE(rate, args) \
  RCLCPP_DEBUG_STREAM_SKIPFIRST_THROTTLE(logger_, rate, RCOMPONENT_STREAM_PREFIX << args)

// ==============================
// INFO
// ==============================

#define RCOMPONENT_INFO(format_string, ...) \
  RCLCPP_INFO(logger_, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_INFO_ONCE(format_string, ...) \
  RCLCPP_INFO_ONCE(logger_, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_INFO_EXPRESSION(cond, format_string, ...) \
  RCLCPP_INFO_EXPRESSION(logger_, cond, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_INFO_FUNCTION(func, format_string, ...) \
  RCLCPP_INFO_FUNCTION(logger_, func, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_INFO_SKIPFIRST(format_string, ...) \
  RCLCPP_INFO_SKIPFIRST(logger_, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_INFO_THROTTLE(rate, format_string, ...) \
  RCLCPP_INFO_THROTTLE(logger_, rate, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_INFO_SKIPFIRST_THROTTLE(rate, format_string, ...) \
  RCLCPP_INFO_SKIPFIRST_THROTTLE(logger_, rate, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_INFO_STREAM(args) \
  RCLCPP_INFO_STREAM(logger_, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_INFO_STREAM_ONCE(args) \
  RCLCPP_INFO_STREAM_ONCE(logger_, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_INFO_STREAM_EXPRESSION(cond, args) \
  RCLCPP_INFO_STREAM_EXPRESSION(logger_, cond, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_INFO_STREAM_FUNCTION(func, args) \
  RCLCPP_INFO_STREAM_FUNCTION(logger_, func, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_INFO_STREAM_SKIPFIRST(args) \
  RCLCPP_INFO_STREAM_SKIPFIRST(logger_, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_INFO_STREAM_THROTTLE(rate, args) \
  RCLCPP_INFO_STREAM_THROTTLE(logger_, rate, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_INFO_STREAM_SKIPFIRST_THROTTLE(rate, args) \
  RCLCPP_INFO_STREAM_SKIPFIRST_THROTTLE(logger_, rate, RCOMPONENT_STREAM_PREFIX << args)

// ==============================
// WARN
// ==============================

#define RCOMPONENT_WARN(format_string, ...) \
  RCLCPP_WARN(logger_, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_WARN_ONCE(format_string, ...) \
  RCLCPP_WARN_ONCE(logger_, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_WARN_EXPRESSION(cond, format_string, ...) \
  RCLCPP_WARN_EXPRESSION(logger_, cond, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_WARN_FUNCTION(func, format_string, ...) \
  RCLCPP_WARN_FUNCTION(logger_, func, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_WARN_SKIPFIRST(format_string, ...) \
  RCLCPP_WARN_SKIPFIRST(logger_, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_WARN_THROTTLE(rate, format_string, ...) \
  RCLCPP_WARN_THROTTLE(logger_, rate, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_WARN_SKIPFIRST_THROTTLE(rate, format_string, ...) \
  RCLCPP_WARN_SKIPFIRST_THROTTLE(logger_, rate, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_WARN_STREAM(args) \
  RCLCPP_WARN_STREAM(logger_, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_WARN_STREAM_ONCE(args) \
  RCLCPP_WARN_STREAM_ONCE(logger_, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_WARN_STREAM_EXPRESSION(cond, args) \
  RCLCPP_WARN_STREAM_EXPRESSION(logger_, cond, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_WARN_STREAM_FUNCTION(func, args) \
  RCLCPP_WARN_STREAM_FUNCTION(logger_, func, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_WARN_STREAM_SKIPFIRST(args) \
  RCLCPP_WARN_STREAM_SKIPFIRST(logger_, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_WARN_STREAM_THROTTLE(rate, args) \
  RCLCPP_WARN_STREAM_THROTTLE(logger_, rate, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_WARN_STREAM_SKIPFIRST_THROTTLE(rate, args) \
  RCLCPP_WARN_STREAM_SKIPFIRST_THROTTLE(logger_, rate, RCOMPONENT_STREAM_PREFIX << args)

// ==============================
// ERROR
// ==============================

#define RCOMPONENT_ERROR(format_string, ...) \
  RCLCPP_ERROR(logger_, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_ERROR_ONCE(format_string, ...) \
  RCLCPP_ERROR_ONCE(logger_, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_ERROR_EXPRESSION(cond, format_string, ...) \
  RCLCPP_ERROR_EXPRESSION(logger_, cond, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_ERROR_FUNCTION(func, format_string, ...) \
  RCLCPP_ERROR_FUNCTION(logger_, func, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_ERROR_SKIPFIRST(format_string, ...) \
  RCLCPP_ERROR_SKIPFIRST(logger_, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_ERROR_THROTTLE(rate, format_string, ...) \
  RCLCPP_ERROR_THROTTLE(logger_, rate, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_ERROR_SKIPFIRST_THROTTLE(rate, format_string, ...) \
  RCLCPP_ERROR_SKIPFIRST_THROTTLE(logger_, rate, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_ERROR_STREAM(args) \
  RCLCPP_ERROR_STREAM(logger_, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_ERROR_STREAM_ONCE(args) \
  RCLCPP_ERROR_STREAM_ONCE(logger_, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_ERROR_STREAM_EXPRESSION(cond, args) \
  RCLCPP_ERROR_STREAM_EXPRESSION(logger_, cond, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_ERROR_STREAM_FUNCTION(func, args) \
  RCLCPP_ERROR_STREAM_FUNCTION(logger_, func, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_ERROR_STREAM_SKIPFIRST(args) \
  RCLCPP_ERROR_STREAM_SKIPFIRST(logger_, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_ERROR_STREAM_THROTTLE(rate, args) \
  RCLCPP_ERROR_STREAM_THROTTLE(logger_, rate, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_ERROR_STREAM_SKIPFIRST_THROTTLE(rate, args) \
  RCLCPP_ERROR_STREAM_SKIPFIRST_THROTTLE(logger_, rate, RCOMPONENT_STREAM_PREFIX << args)

// ==============================
// FATAL
// ==============================

#define RCOMPONENT_FATAL(format_string, ...) \
  RCLCPP_FATAL(logger_, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_FATAL_ONCE(format_string, ...) \
  RCLCPP_FATAL_ONCE(logger_, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_FATAL_EXPRESSION(cond, format_string, ...) \
  RCLCPP_FATAL_EXPRESSION(logger_, cond, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_FATAL_FUNCTION(func, format_string, ...) \
  RCLCPP_FATAL_FUNCTION(logger_, func, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_FATAL_SKIPFIRST(format_string, ...) \
  RCLCPP_FATAL_SKIPFIRST(logger_, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_FATAL_THROTTLE(rate, format_string, ...) \
  RCLCPP_FATAL_THROTTLE(logger_, rate, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_FATAL_SKIPFIRST_THROTTLE(rate, format_string, ...) \
  RCLCPP_FATAL_SKIPFIRST_THROTTLE(logger_, rate, RCOMPONENT_LOG_PREFIX format_string, RCOMPONENT_LOG_ARGS, ##__VA_ARGS__)

#define RCOMPONENT_FATAL_STREAM(args) \
  RCLCPP_FATAL_STREAM(logger_, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_FATAL_STREAM_ONCE(args) \
  RCLCPP_FATAL_STREAM_ONCE(logger_, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_FATAL_STREAM_EXPRESSION(cond, args) \
  RCLCPP_FATAL_STREAM_EXPRESSION(logger_, cond, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_FATAL_STREAM_FUNCTION(func, args) \
  RCLCPP_FATAL_STREAM_FUNCTION(logger_, func, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_FATAL_STREAM_SKIPFIRST(args) \
  RCLCPP_FATAL_STREAM_SKIPFIRST(logger_, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_FATAL_STREAM_THROTTLE(rate, args) \
  RCLCPP_FATAL_STREAM_THROTTLE(logger_, rate, RCOMPONENT_STREAM_PREFIX << args)

#define RCOMPONENT_FATAL_STREAM_SKIPFIRST_THROTTLE(rate, args) \
  RCLCPP_FATAL_STREAM_SKIPFIRST_THROTTLE(logger_, rate, RCOMPONENT_STREAM_PREFIX << args)
