#!/usr/bin/env bash


# USEFUL FORMAT PARAMETERS

bold="\e[1m" 
italic="\e[3m"
underline="\e[4m"
reset="\e[0m"

black="\e[1;30m"
blue="\e[1;34m"
cyan="\e[1;36m"
green="\e[1;32m"
orange="\e[1;33m"
purple="\e[1;35m"
red="\e[1;31m"
white="\e[1;37m"
yellow="\e[1;33m"

IFS= # Necessary for copying line breaks on cat


# IS USER REQUESTING FOR HELP?

if [ "$1" == "--help" ] || [ "$1" == "-h" ]
then
    echo -e "Usage: $0 [OPTION...]\n"
    echo -e "\toptions:\n"
    echo -e -n "\t-t\tTest mode. Auto-completion of parameters (adition of "
    echo -e    "${italic}MoreTsTest${reset} to ${italic}tester_test${reset} pkg).\n"
    exit 0
fi


# SCRIPT INTRODUCTION

# Request sudo permissions
#sudo clear
#retval=$?
#if [ $retval -ne 0 ]
#then
#    echo -e "\n${bold}${red}You need sudo permissions. Stopping the script."
#    exit 1
#fi

# Introduction to the script
clear
echo -e "\n${bold}${yellow}Welcome to the subnode creator assistant."
echo -e -n "\n${reset}The goal of this script is to simplify the creation of new "
echo -e    "nodes that inherit from others on existing packages."


# LOAD PARAMETERS

# Load templates path
templates_path=`rospack find rcomponent`"/templates"

if [ "$1" == "--test" ] || [ "$1" == "-t" ]
then

    pkg_name=tester_test
    pkg_path=`rospack find tester_test`
    if [[ ! -f $pkg_path"/CMakeLists.txt" ]]
    then
        echo -e -n "\n${bold}${red}You need to create, compile and source "
        echo -e    "the ${italic}${pkg_name}${reset}${bold}${red} package. "
        echo -e    "Stopping the script."
        exit 1
    fi
    ParentNode="TsTest"
    parent_node="ts_test"
    NewNode="MoreTsTest"
    new_node="more_ts_test"
    NEW_NODE=${new_node^^}

else

    # Load destination node name
    echo -e -n "\n${reset}Name of the existing package using snake_case (e.g. "
    echo -e    "${italic}odometry_calibration${reset}): "
    read pkg_name
    pkg_path=`rospack find $pkg_name`
    if [[ ! -f $pkg_path"/CMakeLists.txt" ]]
    then # If node has not been found
        echo -e -n "\n${reset}Package not sourced. Write the complete path to the package. "
        echo -e    "It is required to start with a slash:"
        read pkg_path
        if [[ ! -f $pkg_path"/CMakeLists.txt" ]]
        then
            echo -e -n "\n${bold}${red}The specified path does not contain a ros package. "
            echo -e    "Stopping the script."
            exit 1
        fi
    fi

    # Load ParentNode name
    echo -e -n "\n${reset}Name of the parent class using PascalCase (e.g. "
    echo -e    "${italic}OdomCalibration${reset}): "
    read ParentNode
    if [ -z "$ParentNode" ]
    then
        echo -e "${bold}${red}You have skipped a required argument. Stopping the script."
        exit 1
    fi

    # Load parent_node name
    echo -e -n "\n${reset}Name of the parent class using snake_case (e.g. "
    echo -e    "${italic}odom_calibration${reset}): "
    read parent_node
    if [ ! -f $pkg_path/include/$pkg_name/$parent_node.h ]
    then
        echo -e "${bold}${red}File $parent_node.h not found. Stopping the script."
        exit 1
    fi

    # Load NewNode name
    echo -e -n "\n${reset}Name of the new class using PascalCase (e.g. "
    echo -e    "${italic}DiffOdomCalibration${reset}): "
    read NewNode
    if [ -z "$NewNode" ]
    then
        echo -e "${bold}${red}You have skipped a required argument. Stopping the script."
        exit 1
    fi

    # Load new_node name
    echo -e -n "\n${reset}Name of the new class using snake_case (e.g. "
    echo -e    "${italic}diff_odom_calibration${reset}): "
    read new_node
    if [ -z "$new_node" ]
    then
        echo -e "${bold}${red}You have skipped a required argument. Stopping the script."
        exit 1
    fi

    # Load NEW_NODE name
    NEW_NODE=${new_node^^}

fi

# CREATE FILES

# Create .h
new_node_h="$(cat $templates_path/rc_node.h)"
new_node_h=${new_node_h//"?rc_package"/$pkg_name}
new_node_h=${new_node_h//"<rcomponent/rcomponent.h>"/"<$pkg_name/$parent_node.h>"}
new_node_h=${new_node_h//"?RCNode"/$NewNode}
new_node_h=${new_node_h//"?rc_node"/$new_node}
new_node_h=${new_node_h//"?RC_NODE"/$NEW_NODE}
new_node_h=${new_node_h//"rcomponent::RComponent"/$ParentNode}
new_node_h=${new_node_h//"?authorName"/$authorName}
new_node_h=${new_node_h//"?authorEmail"/$authorEmail}
new_node_h=${new_node_h//"?brief"/$brief}
echo $new_node_h > $pkg_path/include/$pkg_name/$new_node.h
: '
# Create .launch
rc_node_cpp_launch="$(cat $templates_path/rc_node_cpp.launch)"
rc_node_cpp_launch=${rc_node_cpp_launch//"?rc_package"/$rc_package}
rc_node_cpp_launch=${rc_node_cpp_launch//"?RCNode"/$RCNode}
rc_node_cpp_launch=${rc_node_cpp_launch//"?rc_node"/$rc_node}
rc_node_cpp_launch=${rc_node_cpp_launch//"?RC_NODE"/$RC_NODE}
rc_node_cpp_launch=${rc_node_cpp_launch//"?authorName"/$authorName}
rc_node_cpp_launch=${rc_node_cpp_launch//"?authorEmail"/$authorEmail}
rc_node_cpp_launch=${rc_node_cpp_launch//"?brief"/$brief}
echo $rc_node_cpp_launch > $pkg_path/launch/$rc_node"_cpp.launch"

# Create C++ src files
rc_node_cpp="$(cat $templates_path/rc_node.cpp)"
rc_node_cpp=${rc_node_cpp//"?rc_package"/$rc_package}
rc_node_cpp=${rc_node_cpp//"?RCNode"/$RCNode}
rc_node_cpp=${rc_node_cpp//"?rc_node"/$rc_node}
rc_node_cpp=${rc_node_cpp//"?RC_NODE"/$RC_NODE}
rc_node_cpp=${rc_node_cpp//"?authorName"/$authorName}
rc_node_cpp=${rc_node_cpp//"?authorEmail"/$authorEmail}
rc_node_cpp=${rc_node_cpp//"?brief"/$brief}
echo $rc_node_cpp > $pkg_path/src/$rc_node.cpp

rc_node_node_cpp="$(cat $templates_path/rc_node_node.cpp)"
rc_node_node_cpp=${rc_node_node_cpp//"?rc_package"/$rc_package}
rc_node_node_cpp=${rc_node_node_cpp//"?RCNode"/$RCNode}
rc_node_node_cpp=${rc_node_node_cpp//"?rc_node"/$rc_node}
rc_node_node_cpp=${rc_node_node_cpp//"?RC_NODE"/$RC_NODE}
rc_node_node_cpp=${rc_node_node_cpp//"?authorName"/$authorName}
rc_node_node_cpp=${rc_node_node_cpp//"?authorEmail"/$authorEmail}
rc_node_node_cpp=${rc_node_node_cpp//"?brief"/$brief}
echo $rc_node_node_cpp > $pkg_path/src/$rc_node"_node.cpp"
'